// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smartschool.proxies;

public class Alunos implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject alunosMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SmartSchool.Alunos";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Matricula("Matricula"),
		Nome("Nome"),
		Sobrenome("Sobrenome"),
		Data_De_Nascimento("Data_De_Nascimento"),
		Nome_Mae("Nome_Mae"),
		Nome_Pai("Nome_Pai"),
		Endereco("Endereco"),
		Numeracao("Numeracao"),
		Cidade("Cidade"),
		Estado("Estado"),
		CEP("CEP"),
		Destro("Destro"),
		PCD("PCD"),
		Mensalidade("Mensalidade"),
		Alunos_Serie("SmartSchool.Alunos_Serie");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Alunos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Alunos(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject alunosMendixObject)
	{
		if (alunosMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, alunosMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.alunosMendixObject = alunosMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smartschool.proxies.Alunos initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smartschool.proxies.Alunos(context, mendixObject);
	}

	public static smartschool.proxies.Alunos load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smartschool.proxies.Alunos.initialize(context, mendixObject);
	}

	public static java.util.List<smartschool.proxies.Alunos> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smartschool.proxies.Alunos.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Matricula
	 */
	public final java.lang.Long getMatricula()
	{
		return getMatricula(getContext());
	}

	/**
	 * @param context
	 * @return value of Matricula
	 */
	public final java.lang.Long getMatricula(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Matricula.toString());
	}

	/**
	 * Set value of Matricula
	 * @param matricula
	 */
	public final void setMatricula(java.lang.Long matricula)
	{
		setMatricula(getContext(), matricula);
	}

	/**
	 * Set value of Matricula
	 * @param context
	 * @param matricula
	 */
	public final void setMatricula(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long matricula)
	{
		getMendixObject().setValue(context, MemberNames.Matricula.toString(), matricula);
	}

	/**
	 * @return value of Nome
	 */
	public final java.lang.String getNome()
	{
		return getNome(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome
	 */
	public final java.lang.String getNome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome.toString());
	}

	/**
	 * Set value of Nome
	 * @param nome
	 */
	public final void setNome(java.lang.String nome)
	{
		setNome(getContext(), nome);
	}

	/**
	 * Set value of Nome
	 * @param context
	 * @param nome
	 */
	public final void setNome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome)
	{
		getMendixObject().setValue(context, MemberNames.Nome.toString(), nome);
	}

	/**
	 * @return value of Sobrenome
	 */
	public final java.lang.String getSobrenome()
	{
		return getSobrenome(getContext());
	}

	/**
	 * @param context
	 * @return value of Sobrenome
	 */
	public final java.lang.String getSobrenome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sobrenome.toString());
	}

	/**
	 * Set value of Sobrenome
	 * @param sobrenome
	 */
	public final void setSobrenome(java.lang.String sobrenome)
	{
		setSobrenome(getContext(), sobrenome);
	}

	/**
	 * Set value of Sobrenome
	 * @param context
	 * @param sobrenome
	 */
	public final void setSobrenome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sobrenome)
	{
		getMendixObject().setValue(context, MemberNames.Sobrenome.toString(), sobrenome);
	}

	/**
	 * @return value of Data_De_Nascimento
	 */
	public final java.util.Date getData_De_Nascimento()
	{
		return getData_De_Nascimento(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_De_Nascimento
	 */
	public final java.util.Date getData_De_Nascimento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Data_De_Nascimento.toString());
	}

	/**
	 * Set value of Data_De_Nascimento
	 * @param data_de_nascimento
	 */
	public final void setData_De_Nascimento(java.util.Date data_de_nascimento)
	{
		setData_De_Nascimento(getContext(), data_de_nascimento);
	}

	/**
	 * Set value of Data_De_Nascimento
	 * @param context
	 * @param data_de_nascimento
	 */
	public final void setData_De_Nascimento(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date data_de_nascimento)
	{
		getMendixObject().setValue(context, MemberNames.Data_De_Nascimento.toString(), data_de_nascimento);
	}

	/**
	 * @return value of Nome_Mae
	 */
	public final java.lang.String getNome_Mae()
	{
		return getNome_Mae(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome_Mae
	 */
	public final java.lang.String getNome_Mae(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome_Mae.toString());
	}

	/**
	 * Set value of Nome_Mae
	 * @param nome_mae
	 */
	public final void setNome_Mae(java.lang.String nome_mae)
	{
		setNome_Mae(getContext(), nome_mae);
	}

	/**
	 * Set value of Nome_Mae
	 * @param context
	 * @param nome_mae
	 */
	public final void setNome_Mae(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome_mae)
	{
		getMendixObject().setValue(context, MemberNames.Nome_Mae.toString(), nome_mae);
	}

	/**
	 * @return value of Nome_Pai
	 */
	public final java.lang.String getNome_Pai()
	{
		return getNome_Pai(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome_Pai
	 */
	public final java.lang.String getNome_Pai(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome_Pai.toString());
	}

	/**
	 * Set value of Nome_Pai
	 * @param nome_pai
	 */
	public final void setNome_Pai(java.lang.String nome_pai)
	{
		setNome_Pai(getContext(), nome_pai);
	}

	/**
	 * Set value of Nome_Pai
	 * @param context
	 * @param nome_pai
	 */
	public final void setNome_Pai(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome_pai)
	{
		getMendixObject().setValue(context, MemberNames.Nome_Pai.toString(), nome_pai);
	}

	/**
	 * @return value of Endereco
	 */
	public final java.lang.String getEndereco()
	{
		return getEndereco(getContext());
	}

	/**
	 * @param context
	 * @return value of Endereco
	 */
	public final java.lang.String getEndereco(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Endereco.toString());
	}

	/**
	 * Set value of Endereco
	 * @param endereco
	 */
	public final void setEndereco(java.lang.String endereco)
	{
		setEndereco(getContext(), endereco);
	}

	/**
	 * Set value of Endereco
	 * @param context
	 * @param endereco
	 */
	public final void setEndereco(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endereco)
	{
		getMendixObject().setValue(context, MemberNames.Endereco.toString(), endereco);
	}

	/**
	 * @return value of Numeracao
	 */
	public final java.lang.Integer getNumeracao()
	{
		return getNumeracao(getContext());
	}

	/**
	 * @param context
	 * @return value of Numeracao
	 */
	public final java.lang.Integer getNumeracao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Numeracao.toString());
	}

	/**
	 * Set value of Numeracao
	 * @param numeracao
	 */
	public final void setNumeracao(java.lang.Integer numeracao)
	{
		setNumeracao(getContext(), numeracao);
	}

	/**
	 * Set value of Numeracao
	 * @param context
	 * @param numeracao
	 */
	public final void setNumeracao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numeracao)
	{
		getMendixObject().setValue(context, MemberNames.Numeracao.toString(), numeracao);
	}

	/**
	 * @return value of Cidade
	 */
	public final java.lang.String getCidade()
	{
		return getCidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Cidade
	 */
	public final java.lang.String getCidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cidade.toString());
	}

	/**
	 * Set value of Cidade
	 * @param cidade
	 */
	public final void setCidade(java.lang.String cidade)
	{
		setCidade(getContext(), cidade);
	}

	/**
	 * Set value of Cidade
	 * @param context
	 * @param cidade
	 */
	public final void setCidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cidade)
	{
		getMendixObject().setValue(context, MemberNames.Cidade.toString(), cidade);
	}

	/**
	 * @return value of Estado
	 */
	public final java.lang.String getEstado()
	{
		return getEstado(getContext());
	}

	/**
	 * @param context
	 * @return value of Estado
	 */
	public final java.lang.String getEstado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Estado.toString());
	}

	/**
	 * Set value of Estado
	 * @param estado
	 */
	public final void setEstado(java.lang.String estado)
	{
		setEstado(getContext(), estado);
	}

	/**
	 * Set value of Estado
	 * @param context
	 * @param estado
	 */
	public final void setEstado(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String estado)
	{
		getMendixObject().setValue(context, MemberNames.Estado.toString(), estado);
	}

	/**
	 * @return value of CEP
	 */
	public final java.lang.String getCEP()
	{
		return getCEP(getContext());
	}

	/**
	 * @param context
	 * @return value of CEP
	 */
	public final java.lang.String getCEP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CEP.toString());
	}

	/**
	 * Set value of CEP
	 * @param cep
	 */
	public final void setCEP(java.lang.String cep)
	{
		setCEP(getContext(), cep);
	}

	/**
	 * Set value of CEP
	 * @param context
	 * @param cep
	 */
	public final void setCEP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cep)
	{
		getMendixObject().setValue(context, MemberNames.CEP.toString(), cep);
	}

	/**
	 * @return value of Destro
	 */
	public final java.lang.Boolean getDestro()
	{
		return getDestro(getContext());
	}

	/**
	 * @param context
	 * @return value of Destro
	 */
	public final java.lang.Boolean getDestro(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Destro.toString());
	}

	/**
	 * Set value of Destro
	 * @param destro
	 */
	public final void setDestro(java.lang.Boolean destro)
	{
		setDestro(getContext(), destro);
	}

	/**
	 * Set value of Destro
	 * @param context
	 * @param destro
	 */
	public final void setDestro(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean destro)
	{
		getMendixObject().setValue(context, MemberNames.Destro.toString(), destro);
	}

	/**
	 * @return value of PCD
	 */
	public final java.lang.String getPCD()
	{
		return getPCD(getContext());
	}

	/**
	 * @param context
	 * @return value of PCD
	 */
	public final java.lang.String getPCD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PCD.toString());
	}

	/**
	 * Set value of PCD
	 * @param pcd
	 */
	public final void setPCD(java.lang.String pcd)
	{
		setPCD(getContext(), pcd);
	}

	/**
	 * Set value of PCD
	 * @param context
	 * @param pcd
	 */
	public final void setPCD(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pcd)
	{
		getMendixObject().setValue(context, MemberNames.PCD.toString(), pcd);
	}

	/**
	 * @return value of Mensalidade
	 */
	public final java.math.BigDecimal getMensalidade()
	{
		return getMensalidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Mensalidade
	 */
	public final java.math.BigDecimal getMensalidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Mensalidade.toString());
	}

	/**
	 * Set value of Mensalidade
	 * @param mensalidade
	 */
	public final void setMensalidade(java.math.BigDecimal mensalidade)
	{
		setMensalidade(getContext(), mensalidade);
	}

	/**
	 * Set value of Mensalidade
	 * @param context
	 * @param mensalidade
	 */
	public final void setMensalidade(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal mensalidade)
	{
		getMendixObject().setValue(context, MemberNames.Mensalidade.toString(), mensalidade);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Alunos_Serie
	 */
	public final smartschool.proxies.Serie getAlunos_Serie() throws com.mendix.core.CoreException
	{
		return getAlunos_Serie(getContext());
	}

	/**
	 * @param context
	 * @return value of Alunos_Serie
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.Serie getAlunos_Serie(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.Serie result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Alunos_Serie.toString());
		if (identifier != null) {
			result = smartschool.proxies.Serie.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Alunos_Serie
	 * @param alunos_serie
	 */
	public final void setAlunos_Serie(smartschool.proxies.Serie alunos_serie)
	{
		setAlunos_Serie(getContext(), alunos_serie);
	}

	/**
	 * Set value of Alunos_Serie
	 * @param context
	 * @param alunos_serie
	 */
	public final void setAlunos_Serie(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.Serie alunos_serie)
	{
		if (alunos_serie == null) {
			getMendixObject().setValue(context, MemberNames.Alunos_Serie.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Alunos_Serie.toString(), alunos_serie.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return alunosMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smartschool.proxies.Alunos that = (smartschool.proxies.Alunos) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
