// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smartschool.proxies;

public class Apontamento implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject apontamentoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SmartSchool.Apontamento";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nome_Responsavel("Nome_Responsavel"),
		Motivo("Motivo"),
		Data_Hora("Data_Hora"),
		Nome_Professor("Nome_Professor"),
		Nome_Aluno("Nome_Aluno");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Apontamento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Apontamento(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject apontamentoMendixObject)
	{
		if (apontamentoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, apontamentoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.apontamentoMendixObject = apontamentoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smartschool.proxies.Apontamento initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smartschool.proxies.Apontamento(context, mendixObject);
	}

	public static smartschool.proxies.Apontamento load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smartschool.proxies.Apontamento.initialize(context, mendixObject);
	}

	public static java.util.List<smartschool.proxies.Apontamento> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smartschool.proxies.Apontamento.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Nome_Responsavel
	 */
	public final java.lang.String getNome_Responsavel()
	{
		return getNome_Responsavel(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome_Responsavel
	 */
	public final java.lang.String getNome_Responsavel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome_Responsavel.toString());
	}

	/**
	 * Set value of Nome_Responsavel
	 * @param nome_responsavel
	 */
	public final void setNome_Responsavel(java.lang.String nome_responsavel)
	{
		setNome_Responsavel(getContext(), nome_responsavel);
	}

	/**
	 * Set value of Nome_Responsavel
	 * @param context
	 * @param nome_responsavel
	 */
	public final void setNome_Responsavel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome_responsavel)
	{
		getMendixObject().setValue(context, MemberNames.Nome_Responsavel.toString(), nome_responsavel);
	}

	/**
	 * @return value of Motivo
	 */
	public final java.lang.String getMotivo()
	{
		return getMotivo(getContext());
	}

	/**
	 * @param context
	 * @return value of Motivo
	 */
	public final java.lang.String getMotivo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Motivo.toString());
	}

	/**
	 * Set value of Motivo
	 * @param motivo
	 */
	public final void setMotivo(java.lang.String motivo)
	{
		setMotivo(getContext(), motivo);
	}

	/**
	 * Set value of Motivo
	 * @param context
	 * @param motivo
	 */
	public final void setMotivo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motivo)
	{
		getMendixObject().setValue(context, MemberNames.Motivo.toString(), motivo);
	}

	/**
	 * @return value of Data_Hora
	 */
	public final java.util.Date getData_Hora()
	{
		return getData_Hora(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_Hora
	 */
	public final java.util.Date getData_Hora(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Data_Hora.toString());
	}

	/**
	 * Set value of Data_Hora
	 * @param data_hora
	 */
	public final void setData_Hora(java.util.Date data_hora)
	{
		setData_Hora(getContext(), data_hora);
	}

	/**
	 * Set value of Data_Hora
	 * @param context
	 * @param data_hora
	 */
	public final void setData_Hora(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date data_hora)
	{
		getMendixObject().setValue(context, MemberNames.Data_Hora.toString(), data_hora);
	}

	/**
	 * @return value of Nome_Professor
	 */
	public final java.lang.String getNome_Professor()
	{
		return getNome_Professor(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome_Professor
	 */
	public final java.lang.String getNome_Professor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome_Professor.toString());
	}

	/**
	 * Set value of Nome_Professor
	 * @param nome_professor
	 */
	public final void setNome_Professor(java.lang.String nome_professor)
	{
		setNome_Professor(getContext(), nome_professor);
	}

	/**
	 * Set value of Nome_Professor
	 * @param context
	 * @param nome_professor
	 */
	public final void setNome_Professor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome_professor)
	{
		getMendixObject().setValue(context, MemberNames.Nome_Professor.toString(), nome_professor);
	}

	/**
	 * @return value of Nome_Aluno
	 */
	public final java.lang.String getNome_Aluno()
	{
		return getNome_Aluno(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome_Aluno
	 */
	public final java.lang.String getNome_Aluno(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome_Aluno.toString());
	}

	/**
	 * Set value of Nome_Aluno
	 * @param nome_aluno
	 */
	public final void setNome_Aluno(java.lang.String nome_aluno)
	{
		setNome_Aluno(getContext(), nome_aluno);
	}

	/**
	 * Set value of Nome_Aluno
	 * @param context
	 * @param nome_aluno
	 */
	public final void setNome_Aluno(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome_aluno)
	{
		getMendixObject().setValue(context, MemberNames.Nome_Aluno.toString(), nome_aluno);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return apontamentoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smartschool.proxies.Apontamento that = (smartschool.proxies.Apontamento) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
