// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smartschool.proxies;

public class FotoProfessor extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SmartSchool.FotoProfessor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Professores_FotoProfessor("SmartSchool.Professores_FotoProfessor"),
		FotoProfessor_Account("SmartSchool.FotoProfessor_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FotoProfessor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FotoProfessor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fotoProfessorMendixObject)
	{
		super(context, fotoProfessorMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, fotoProfessorMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smartschool.proxies.FotoProfessor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smartschool.proxies.FotoProfessor(context, mendixObject);
	}

	public static smartschool.proxies.FotoProfessor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smartschool.proxies.FotoProfessor.initialize(context, mendixObject);
	}

	public static java.util.List<smartschool.proxies.FotoProfessor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smartschool.proxies.FotoProfessor.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Professores_FotoProfessor
	 */
	public final smartschool.proxies.Professores getProfessores_FotoProfessor() throws com.mendix.core.CoreException
	{
		return getProfessores_FotoProfessor(getContext());
	}

	/**
	 * @param context
	 * @return value of Professores_FotoProfessor
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.Professores getProfessores_FotoProfessor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.Professores result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Professores_FotoProfessor.toString());
		if (identifier != null) {
			result = smartschool.proxies.Professores.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Professores_FotoProfessor
	 * @param professores_fotoprofessor
	 */
	public final void setProfessores_FotoProfessor(smartschool.proxies.Professores professores_fotoprofessor)
	{
		setProfessores_FotoProfessor(getContext(), professores_fotoprofessor);
	}

	/**
	 * Set value of Professores_FotoProfessor
	 * @param context
	 * @param professores_fotoprofessor
	 */
	public final void setProfessores_FotoProfessor(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.Professores professores_fotoprofessor)
	{
		if (professores_fotoprofessor == null) {
			getMendixObject().setValue(context, MemberNames.Professores_FotoProfessor.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Professores_FotoProfessor.toString(), professores_fotoprofessor.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FotoProfessor_Account
	 */
	public final administration.proxies.Account getFotoProfessor_Account() throws com.mendix.core.CoreException
	{
		return getFotoProfessor_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of FotoProfessor_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getFotoProfessor_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FotoProfessor_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FotoProfessor_Account
	 * @param fotoprofessor_account
	 */
	public final void setFotoProfessor_Account(administration.proxies.Account fotoprofessor_account)
	{
		setFotoProfessor_Account(getContext(), fotoprofessor_account);
	}

	/**
	 * Set value of FotoProfessor_Account
	 * @param context
	 * @param fotoprofessor_account
	 */
	public final void setFotoProfessor_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account fotoprofessor_account)
	{
		if (fotoprofessor_account == null) {
			getMendixObject().setValue(context, MemberNames.FotoProfessor_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FotoProfessor_Account.toString(), fotoprofessor_account.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smartschool.proxies.FotoProfessor that = (smartschool.proxies.FotoProfessor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
