// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smartschool.proxies;

public class Postagem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject postagemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SmartSchool.Postagem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Titulo("Titulo"),
		Autor("Autor"),
		Descricao("Descricao"),
		Link_Auxiliar("Link_Auxiliar");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Postagem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Postagem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject postagemMendixObject)
	{
		if (postagemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, postagemMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.postagemMendixObject = postagemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smartschool.proxies.Postagem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smartschool.proxies.Postagem(context, mendixObject);
	}

	public static smartschool.proxies.Postagem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smartschool.proxies.Postagem.initialize(context, mendixObject);
	}

	public static java.util.List<smartschool.proxies.Postagem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smartschool.proxies.Postagem.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Titulo
	 */
	public final java.lang.String getTitulo()
	{
		return getTitulo(getContext());
	}

	/**
	 * @param context
	 * @return value of Titulo
	 */
	public final java.lang.String getTitulo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Titulo.toString());
	}

	/**
	 * Set value of Titulo
	 * @param titulo
	 */
	public final void setTitulo(java.lang.String titulo)
	{
		setTitulo(getContext(), titulo);
	}

	/**
	 * Set value of Titulo
	 * @param context
	 * @param titulo
	 */
	public final void setTitulo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titulo)
	{
		getMendixObject().setValue(context, MemberNames.Titulo.toString(), titulo);
	}

	/**
	 * @return value of Autor
	 */
	public final java.lang.String getAutor()
	{
		return getAutor(getContext());
	}

	/**
	 * @param context
	 * @return value of Autor
	 */
	public final java.lang.String getAutor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Autor.toString());
	}

	/**
	 * Set value of Autor
	 * @param autor
	 */
	public final void setAutor(java.lang.String autor)
	{
		setAutor(getContext(), autor);
	}

	/**
	 * Set value of Autor
	 * @param context
	 * @param autor
	 */
	public final void setAutor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String autor)
	{
		getMendixObject().setValue(context, MemberNames.Autor.toString(), autor);
	}

	/**
	 * @return value of Descricao
	 */
	public final java.lang.String getDescricao()
	{
		return getDescricao(getContext());
	}

	/**
	 * @param context
	 * @return value of Descricao
	 */
	public final java.lang.String getDescricao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Descricao.toString());
	}

	/**
	 * Set value of Descricao
	 * @param descricao
	 */
	public final void setDescricao(java.lang.String descricao)
	{
		setDescricao(getContext(), descricao);
	}

	/**
	 * Set value of Descricao
	 * @param context
	 * @param descricao
	 */
	public final void setDescricao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descricao)
	{
		getMendixObject().setValue(context, MemberNames.Descricao.toString(), descricao);
	}

	/**
	 * @return value of Link_Auxiliar
	 */
	public final java.lang.String getLink_Auxiliar()
	{
		return getLink_Auxiliar(getContext());
	}

	/**
	 * @param context
	 * @return value of Link_Auxiliar
	 */
	public final java.lang.String getLink_Auxiliar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Link_Auxiliar.toString());
	}

	/**
	 * Set value of Link_Auxiliar
	 * @param link_auxiliar
	 */
	public final void setLink_Auxiliar(java.lang.String link_auxiliar)
	{
		setLink_Auxiliar(getContext(), link_auxiliar);
	}

	/**
	 * Set value of Link_Auxiliar
	 * @param context
	 * @param link_auxiliar
	 */
	public final void setLink_Auxiliar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String link_auxiliar)
	{
		getMendixObject().setValue(context, MemberNames.Link_Auxiliar.toString(), link_auxiliar);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return postagemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smartschool.proxies.Postagem that = (smartschool.proxies.Postagem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
