// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smartschool.proxies;

public class Professores implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject professoresMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SmartSchool.Professores";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nome("Nome"),
		Sobrenome("Sobrenome"),
		Data_De_Nascimento("Data_De_Nascimento"),
		Cidade("Cidade"),
		Estado("Estado"),
		Professores_FotoProfessor("SmartSchool.Professores_FotoProfessor"),
		Professores_Alunos("SmartSchool.Professores_Alunos"),
		Professores_Postagem("SmartSchool.Professores_Postagem");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Professores(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Professores(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject professoresMendixObject)
	{
		if (professoresMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, professoresMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.professoresMendixObject = professoresMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smartschool.proxies.Professores initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smartschool.proxies.Professores(context, mendixObject);
	}

	public static smartschool.proxies.Professores load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smartschool.proxies.Professores.initialize(context, mendixObject);
	}

	public static java.util.List<smartschool.proxies.Professores> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smartschool.proxies.Professores.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Nome
	 */
	public final java.lang.String getNome()
	{
		return getNome(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome
	 */
	public final java.lang.String getNome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome.toString());
	}

	/**
	 * Set value of Nome
	 * @param nome
	 */
	public final void setNome(java.lang.String nome)
	{
		setNome(getContext(), nome);
	}

	/**
	 * Set value of Nome
	 * @param context
	 * @param nome
	 */
	public final void setNome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome)
	{
		getMendixObject().setValue(context, MemberNames.Nome.toString(), nome);
	}

	/**
	 * @return value of Sobrenome
	 */
	public final java.lang.String getSobrenome()
	{
		return getSobrenome(getContext());
	}

	/**
	 * @param context
	 * @return value of Sobrenome
	 */
	public final java.lang.String getSobrenome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sobrenome.toString());
	}

	/**
	 * Set value of Sobrenome
	 * @param sobrenome
	 */
	public final void setSobrenome(java.lang.String sobrenome)
	{
		setSobrenome(getContext(), sobrenome);
	}

	/**
	 * Set value of Sobrenome
	 * @param context
	 * @param sobrenome
	 */
	public final void setSobrenome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sobrenome)
	{
		getMendixObject().setValue(context, MemberNames.Sobrenome.toString(), sobrenome);
	}

	/**
	 * @return value of Data_De_Nascimento
	 */
	public final java.util.Date getData_De_Nascimento()
	{
		return getData_De_Nascimento(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_De_Nascimento
	 */
	public final java.util.Date getData_De_Nascimento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Data_De_Nascimento.toString());
	}

	/**
	 * Set value of Data_De_Nascimento
	 * @param data_de_nascimento
	 */
	public final void setData_De_Nascimento(java.util.Date data_de_nascimento)
	{
		setData_De_Nascimento(getContext(), data_de_nascimento);
	}

	/**
	 * Set value of Data_De_Nascimento
	 * @param context
	 * @param data_de_nascimento
	 */
	public final void setData_De_Nascimento(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date data_de_nascimento)
	{
		getMendixObject().setValue(context, MemberNames.Data_De_Nascimento.toString(), data_de_nascimento);
	}

	/**
	 * @return value of Cidade
	 */
	public final java.lang.String getCidade()
	{
		return getCidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Cidade
	 */
	public final java.lang.String getCidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cidade.toString());
	}

	/**
	 * Set value of Cidade
	 * @param cidade
	 */
	public final void setCidade(java.lang.String cidade)
	{
		setCidade(getContext(), cidade);
	}

	/**
	 * Set value of Cidade
	 * @param context
	 * @param cidade
	 */
	public final void setCidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cidade)
	{
		getMendixObject().setValue(context, MemberNames.Cidade.toString(), cidade);
	}

	/**
	 * @return value of Estado
	 */
	public final java.lang.String getEstado()
	{
		return getEstado(getContext());
	}

	/**
	 * @param context
	 * @return value of Estado
	 */
	public final java.lang.String getEstado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Estado.toString());
	}

	/**
	 * Set value of Estado
	 * @param estado
	 */
	public final void setEstado(java.lang.String estado)
	{
		setEstado(getContext(), estado);
	}

	/**
	 * Set value of Estado
	 * @param context
	 * @param estado
	 */
	public final void setEstado(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String estado)
	{
		getMendixObject().setValue(context, MemberNames.Estado.toString(), estado);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Professores_FotoProfessor
	 */
	public final smartschool.proxies.FotoProfessor getProfessores_FotoProfessor() throws com.mendix.core.CoreException
	{
		return getProfessores_FotoProfessor(getContext());
	}

	/**
	 * @param context
	 * @return value of Professores_FotoProfessor
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.FotoProfessor getProfessores_FotoProfessor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.FotoProfessor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Professores_FotoProfessor.toString());
		if (identifier != null) {
			result = smartschool.proxies.FotoProfessor.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Professores_FotoProfessor
	 * @param professores_fotoprofessor
	 */
	public final void setProfessores_FotoProfessor(smartschool.proxies.FotoProfessor professores_fotoprofessor)
	{
		setProfessores_FotoProfessor(getContext(), professores_fotoprofessor);
	}

	/**
	 * Set value of Professores_FotoProfessor
	 * @param context
	 * @param professores_fotoprofessor
	 */
	public final void setProfessores_FotoProfessor(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.FotoProfessor professores_fotoprofessor)
	{
		if (professores_fotoprofessor == null) {
			getMendixObject().setValue(context, MemberNames.Professores_FotoProfessor.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Professores_FotoProfessor.toString(), professores_fotoprofessor.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Professores_Alunos
	 */
	public final smartschool.proxies.Alunos getProfessores_Alunos() throws com.mendix.core.CoreException
	{
		return getProfessores_Alunos(getContext());
	}

	/**
	 * @param context
	 * @return value of Professores_Alunos
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.Alunos getProfessores_Alunos(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.Alunos result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Professores_Alunos.toString());
		if (identifier != null) {
			result = smartschool.proxies.Alunos.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Professores_Alunos
	 * @param professores_alunos
	 */
	public final void setProfessores_Alunos(smartschool.proxies.Alunos professores_alunos)
	{
		setProfessores_Alunos(getContext(), professores_alunos);
	}

	/**
	 * Set value of Professores_Alunos
	 * @param context
	 * @param professores_alunos
	 */
	public final void setProfessores_Alunos(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.Alunos professores_alunos)
	{
		if (professores_alunos == null) {
			getMendixObject().setValue(context, MemberNames.Professores_Alunos.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Professores_Alunos.toString(), professores_alunos.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Professores_Postagem
	 */
	public final smartschool.proxies.Postagem getProfessores_Postagem() throws com.mendix.core.CoreException
	{
		return getProfessores_Postagem(getContext());
	}

	/**
	 * @param context
	 * @return value of Professores_Postagem
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.Postagem getProfessores_Postagem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.Postagem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Professores_Postagem.toString());
		if (identifier != null) {
			result = smartschool.proxies.Postagem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Professores_Postagem
	 * @param professores_postagem
	 */
	public final void setProfessores_Postagem(smartschool.proxies.Postagem professores_postagem)
	{
		setProfessores_Postagem(getContext(), professores_postagem);
	}

	/**
	 * Set value of Professores_Postagem
	 * @param context
	 * @param professores_postagem
	 */
	public final void setProfessores_Postagem(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.Postagem professores_postagem)
	{
		if (professores_postagem == null) {
			getMendixObject().setValue(context, MemberNames.Professores_Postagem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Professores_Postagem.toString(), professores_postagem.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return professoresMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smartschool.proxies.Professores that = (smartschool.proxies.Professores) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
