// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies;

public class Account extends system.proxies.User
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Administration.Account";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		Account_Serie("Administration.Account_Serie"),
		Account_Apontamento("Administration.Account_Apontamento"),
		FotoProfessor_Account("SmartSchool.FotoProfessor_Account"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Account(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Account(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountMendixObject)
	{
		super(context, accountMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, accountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static administration.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new administration.proxies.Account(context, mendixObject);
	}

	public static administration.proxies.Account load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return administration.proxies.Account.initialize(context, mendixObject);
	}

	public static java.util.List<administration.proxies.Account> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> administration.proxies.Account.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser()
	{
		return getIsLocalUser(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLocalUser.toString());
	}

	/**
	 * Set value of IsLocalUser
	 * @param islocaluser
	 */
	public final void setIsLocalUser(java.lang.Boolean islocaluser)
	{
		setIsLocalUser(getContext(), islocaluser);
	}

	/**
	 * Set value of IsLocalUser
	 * @param context
	 * @param islocaluser
	 */
	public final void setIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islocaluser)
	{
		getMendixObject().setValue(context, MemberNames.IsLocalUser.toString(), islocaluser);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Account_Serie
	 */
	public final smartschool.proxies.Serie getAccount_Serie() throws com.mendix.core.CoreException
	{
		return getAccount_Serie(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_Serie
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.Serie getAccount_Serie(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.Serie result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Account_Serie.toString());
		if (identifier != null) {
			result = smartschool.proxies.Serie.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Account_Serie
	 * @param account_serie
	 */
	public final void setAccount_Serie(smartschool.proxies.Serie account_serie)
	{
		setAccount_Serie(getContext(), account_serie);
	}

	/**
	 * Set value of Account_Serie
	 * @param context
	 * @param account_serie
	 */
	public final void setAccount_Serie(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.Serie account_serie)
	{
		if (account_serie == null) {
			getMendixObject().setValue(context, MemberNames.Account_Serie.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Account_Serie.toString(), account_serie.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Account_Apontamento
	 */
	public final smartschool.proxies.Apontamento getAccount_Apontamento() throws com.mendix.core.CoreException
	{
		return getAccount_Apontamento(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_Apontamento
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.Apontamento getAccount_Apontamento(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.Apontamento result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Account_Apontamento.toString());
		if (identifier != null) {
			result = smartschool.proxies.Apontamento.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Account_Apontamento
	 * @param account_apontamento
	 */
	public final void setAccount_Apontamento(smartschool.proxies.Apontamento account_apontamento)
	{
		setAccount_Apontamento(getContext(), account_apontamento);
	}

	/**
	 * Set value of Account_Apontamento
	 * @param context
	 * @param account_apontamento
	 */
	public final void setAccount_Apontamento(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.Apontamento account_apontamento)
	{
		if (account_apontamento == null) {
			getMendixObject().setValue(context, MemberNames.Account_Apontamento.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Account_Apontamento.toString(), account_apontamento.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FotoProfessor_Account
	 */
	public final smartschool.proxies.FotoProfessor getFotoProfessor_Account() throws com.mendix.core.CoreException
	{
		return getFotoProfessor_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of FotoProfessor_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final smartschool.proxies.FotoProfessor getFotoProfessor_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smartschool.proxies.FotoProfessor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FotoProfessor_Account.toString());
		if (identifier != null) {
			result = smartschool.proxies.FotoProfessor.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FotoProfessor_Account
	 * @param fotoprofessor_account
	 */
	public final void setFotoProfessor_Account(smartschool.proxies.FotoProfessor fotoprofessor_account)
	{
		setFotoProfessor_Account(getContext(), fotoprofessor_account);
	}

	/**
	 * Set value of FotoProfessor_Account
	 * @param context
	 * @param fotoprofessor_account
	 */
	public final void setFotoProfessor_Account(com.mendix.systemwideinterfaces.core.IContext context, smartschool.proxies.FotoProfessor fotoprofessor_account)
	{
		if (fotoprofessor_account == null) {
			getMendixObject().setValue(context, MemberNames.FotoProfessor_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FotoProfessor_Account.toString(), fotoprofessor_account.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administration.proxies.Account that = (administration.proxies.Account) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
